name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  remote:
    name: Build for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Apt packages
        if: matrix.os == 'ubuntu-latest'
        id: cache-apt
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          execute_install_scripts: true
          packages: libfuse-dev
          version: 1.0
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}
      - name: Move .ccache
        shell: bash
        run: |
          mkdir -p "$nuitka_cache" .ccache
          mv .ccache "$nuitka_cache/ccache"
        env:
          nuitka_cache: ${{ github.workspace }}/.nuitka
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install dependencies
        shell: bash
        run: |
          pip install wheel
          pip install -r requirements.remote.txt
          pip install nuitka
      - name: Build codexctl
        shell: bash
        run: |
          make test
          make executable
        env:
          nuitka_cache: ${{ github.workspace }}/.nuitka
      - name: Move .ccache
        shell: bash
        run: |
          mv "$nuitka_cache/ccache" .ccache
        env:
          nuitka_cache: ${{ github.workspace }}/.nuitka
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: dist
          if-no-files-found: error
  device:
    name: Build for remarkable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codexctl repository
        uses: actions/checkout@v4
      - name: Nuitka ccache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.nuitka
          key: ${{ github.job }}-remarkable-2.15.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build executable
        shell: bash
        run: |
          docker run \
            --rm \
            --platform=linux/arm/v7 \
            -v "${src_path}":/src \
            eeems/nuitka-arm-builder:bullseye-11 \
            bash -ec "$script" # 2>&1 \
          # | while read -r line; do
          #   if [[ "$line" == 'Nuitka'*':ERROR:'* ]]; then
          #     echo "::error file=${{ steps.args.outputs.main_file }},title=Nuitka Error::$line"
          #   elif [[ "$line" == 'Nuitka'*':WARNING:'* ]]; then
          #     echo "::warning file=${{ steps.args.outputs.main_file }},title=Nuitka Warning::$line"
          #   elif [[ "$line" == 'Nuitka:INFO:'* ]]; then
          #     echo "$line"
          #   else
          #     echo "::debug::$line"
          #   fi
          done
        env:
          src_path: ${{ github.workspace }}
          script: |
            apt update
            apt install -y \
              libfuse-dev
            cd /src
            make test
            make executable
      - uses: actions/upload-artifact@v3
        with:
          name: remarkable-2.15.1
          path: dist
          if-no-files-found: error
  release:
    name: Release
    needs: [remote,device]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Set current date as env variable
        run: |
          echo "NAME=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Rename artifacts
        run: |
          ls artifacts | while read artifact; do
            pushd artifacts/${artifact}
            zip -r ../${artifact}.zip .
            popd
          done
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*.zip"
          name: ${{ env.NAME }}
          tag: ${{ env.TAG }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true
          makeLatest: true
